name: Validate Documentation

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '.github/workflows/validate-docs.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'docs/**'
      - '.github/workflows/validate-docs.yml'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: Run documentation validator
      run: |
        python docs/validation/documentation_validator.py
        
    - name: Upload validation results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: documentation-validation-results
        path: |
          docs/validation/*.log
          docs/validation/*.txt
        
    - name: Create validation report
      if: always()
      run: |
        echo "Documentation Validation Report" > validation-report.md
        echo "=============================" >> validation-report.md
        echo "" >> validation-report.md
        echo "Generated on: $(date)" >> validation-report.md
        echo "" >> validation-report.md
        echo "### Summary" >> validation-report.md
        echo "" >> validation-report.md
        echo "- Total files checked: $(find docs -name "*.md" | wc -l)" >> validation-report.md
        echo "- Errors: $(grep -c "ERROR" docs/validation/validation.log)" >> validation-report.md
        echo "- Warnings: $(grep -c "WARNING" docs/validation/validation.log)" >> validation-report.md
        echo "" >> validation-report.md
        echo "### Detailed Results" >> validation-report.md
        echo "" >> validation-report.md
        cat docs/validation/validation.log >> validation-report.md
        
    - name: Upload validation report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: validation-report
        path: validation-report.md
        
    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const report = fs.readFileSync('validation-report.md', 'utf8');
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## Documentation Validation Report\n\n${report}`
          }); 